services:
  bot:
    build: .
    container_name: the-great-work-bot
    restart: unless-stopped
    depends_on:
      - qdrant
    env_file:
      - .env
    environment:
      - GREAT_WORK_DB=/app/var/state/great_work.db
    volumes:
      - ./${GREAT_WORK_ARCHIVE_PUBLISH_DIR:-public}:/app/${GREAT_WORK_ARCHIVE_PUBLISH_DIR:-public}:Z
      - ./var:/app/var:Z
      - ./calibration_snapshots:/app/calibration_snapshots:Z
      # Mount Guardian model weights for local moderation mode
      - ./models/guardian:/app/models/guardian:Z,ro
  qdrant:
    image: qdrant/qdrant:latest
    container_name: the-great-work-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__GRPC_PORT=6334

  archive_server:
    image: nginx:1.27-alpine
    container_name: great-work-archive
    restart: unless-stopped
    depends_on: []
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:Z,ro

  telemetry_dashboard:
    build:
      context: .
      dockerfile: ops/telemetry-dashboard/Dockerfile
    container_name: great-work-telemetry
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./var/telemetry/telemetry.db:/data/telemetry.db:Z,ro
      - ./calibration_snapshots:/data/calibration_snapshots:Z,ro

  # Optional: PostgreSQL for future expansion beyond SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: great-work-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: greatwork
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #     POSTGRES_DB: greatwork
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

networks:
  default:
    name: great-work-network
