name: Publish Archive to Pages

on:
  workflow_dispatch:
  push:
    branches:
      - sprint2
    paths:
      - 'web_archive/**'
      - 'web_archive_public/**'
      - '.github/workflows/publish_pages.yml'

jobs:
  publish:
    name: Sync archive to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate archive payload
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          find_nonempty_dir() {
            local candidate="$1"
            if [ -d "$candidate" ] && [ -n "$(ls -A "$candidate" 2>/dev/null)" ]; then
              echo "$candidate"
            fi
          }

          archive_dir="$(find_nonempty_dir "${GITHUB_WORKSPACE}/web_archive_public")"
          if [ -z "$archive_dir" ]; then
            archive_dir="$(find_nonempty_dir "${GITHUB_WORKSPACE}/web_archive")"
          fi

          if [ -z "$archive_dir" ]; then
            echo "No archive content detected; skipping publish step."
            echo "skip=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Using archive directory: $archive_dir"
          printf 'dir=%s\n' "$archive_dir" >> "$GITHUB_OUTPUT"

      - name: Sync to gh-pages
        if: steps.detect.outputs.skip != 'true'
        shell: bash
        env:
          ARCHIVE_DIR: ${{ steps.detect.outputs.dir }}
        run: |
          set -euo pipefail
          TARGET_BRANCH="gh-pages"
          WORKTREE_DIR="$(mktemp -d)"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin "$TARGET_BRANCH" || true
          if git ls-remote --exit-code origin "$TARGET_BRANCH" >/dev/null 2>&1; then
            git worktree add -B "$TARGET_BRANCH" "$WORKTREE_DIR" "origin/$TARGET_BRANCH"
          else
            git worktree add -B "$TARGET_BRANCH" "$WORKTREE_DIR"
          fi

          rsync -av --delete "$ARCHIVE_DIR"/ "$WORKTREE_DIR"/
          touch "$WORKTREE_DIR/.nojekyll"

          pushd "$WORKTREE_DIR" >/dev/null
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to publish."
            popd >/dev/null
            git worktree remove "$WORKTREE_DIR"
            exit 0
          fi

          git add .
          COMMIT_MESSAGE="Publish archive from ${GITHUB_REF##*/} (${GITHUB_SHA::7})"
          git commit -m "$COMMIT_MESSAGE"
          git push origin "$TARGET_BRANCH"
          popd >/dev/null
          git worktree remove "$WORKTREE_DIR"

      - name: Mark publish skipped
        if: steps.detect.outputs.skip == 'true'
        run: echo "Publish step skipped – archive directory empty."
